FROM tiangolo/uvicorn-gunicorn-fastapi:python3.9

EXPOSE 80

RUN python -m pip install --upgrade pip

COPY ./requirements_api.txt /app/requirements.txt

RUN pip install -r /app/requirements.txt

RUN pip install torch

COPY ./models /app/models

COPY ./api /app/api

CMD ["uvicorn", "api.app:app", "--host", "0.0.0.0", "--port", "80"]
